//board.h
#ifndef __BOARD_H
#define __BOARD_H

#define LED_PORT	GPIOC
#define LED_PIN		GPIO_PIN_5

#define PWR_VDD5V_SW_PORT	GPIOB
#define PWR_VDD5V_SW_PIN	GPIO_PIN_1

#define CTS0_PORT	GPIOA
#define CTS0_PIN	GPIO_PIN_0
	   
#define RXD1_PORT	GPIOA
#define RXD1_PIN	GPIO_PIN_10

#define TXD0_PORT	GPIOA
#define TXD0_PIN	GPIO_PIN_2

#define RXD0_PORT	GPIOA
#define RXD0_PIN	GPIO_PIN_3

#define TXD1_PORT	GPIOA
#define TXD1_PIN	GPIO_PIN_9
   
#define RTS0_PORT	GPIOA
#define RTS0_PIN	GPIO_PIN_1
      
#define BOOT1_PORT	GPIOB
#define BOOT1_PIN	GPIO_PIN_2

#define BOOT0_PORT	GPIOB
#define BOOT0_PIN	GPIO_PIN_8


#define DAC_OUT_PORT	GPIOA
#define DAC_OUT_PIN		GPIO_PIN_4


#define DDS_CLK_UPD_PORT	GPIOB
#define DDS_CLK_UPD_PIN		GPIO_PIN_7

#define DDS_SER_CLK_PORT	GPIOC
#define DDS_SER_CLK_PIN		GPIO_PIN_10

#define DDS_SER_DATA_PORT	GPIOA
#define DDS_SER_DATA_PIN	GPIO_PIN_12

#define DDS_RESET_PORT	GPIOA
#define DDS_RESET_PIN	GPIO_PIN_15

#define PA_SER_DATA_PORT	GPIOC
#define PA_SER_DATA_PIN		GPIO_PIN_12

#define PA_SER_CLK_PORT		GPIOC
#define PA_SER_CLK_PIN		GPIO_PIN_11

#define PA_SER_LE_PORT	GPIOD
#define PA_SER_LE_PIN	GPIO_PIN_2

#define EN_VPA_PORT	GPIOA
#define EN_VPA_PIN	GPIO_PIN_11

#define PLL_SPI_CLK_PORT	GPIOA
#define PLL_SPI_CLK_PIN		GPIO_PIN_5

#define PLL_SPI_MOSI_PORT	GPIOA
#define PLL_SPI_MOSI_PIN	GPIO_PIN_7

#define PLL_SPI_CS_PORT	GPIOC
#define PLL_SPI_CS_PIN	GPIO_PIN_4
      
#define PLL_MUTE_PORT	GPIOC
#define PLL_MUTE_PIN	GPIO_PIN_1

#define PLL_MUXOUT_PORT	GPIOC
#define PLL_MUXOUT_PIN	GPIO_PIN_3

#define PLL_LD_PORT	GPIOC
#define PLL_LD_PIN	GPIO_PIN_2

#define FILTER_CTRL0_PORT	GPIOC
#define FILTER_CTRL0_PIN	GPIO_PIN_9

#define FILTER_CTRL1_PORT	GPIOC
#define FILTER_CTRL1_PIN	GPIO_PIN_8

#define FILTER_CTRL2_PORT	GPIOC
#define FILTER_CTRL2_PIN	GPIO_PIN_7

#define FILTER_CTRL3_PORT	GPIOC
#define FILTER_CTRL3_PIN	GPIO_PIN_6

#define FILTER_CTRL4_PORT	GPIOB
#define FILTER_CTRL4_PIN	GPIO_PIN_15

#define FILTER_CTRL6_PORT	GPIOB
#define FILTER_CTRL6_PIN	GPIO_PIN_13

#define FILTER_CTRL5_PORT	GPIOB
#define FILTER_CTRL5_PIN	GPIO_PIN_14

#define FILTER_CTRL7_PORT	GPIOB
#define FILTER_CTRL7_PIN	GPIO_PIN_12


#define SPI_MISO_PORT	GPIOA
#define SPI_MISO_PIN	GPIO_PIN_6
      
#define FLASH_CS_PORT	GPIOB
#define FLASH_CS_PIN	GPIO_PIN_0

#define FLASH_WP_PORT	GPIOB
#define FLASH_WP_PIN	GPIO_PIN_11

#define CLK_SRC_SELECT_2_PORT	GPIOC
#define CLK_SRC_SELECT_2_PIN	GPIO_PIN_13

#define CLK_SRC_SELECT_0_PORT	GPIOC
#define CLK_SRC_SELECT_0_PIN	GPIO_PIN_15

#define CLK_SRC_SELECT_1_PORT	GPIOC
#define CLK_SRC_SELECT_1_PIN	GPIO_PIN_14

#define BEEP_PORT	GPIOA
#define BEEP_PIN	GPIO_PIN_8


#endif
//led pc5